[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lazy_static = "1.4"
packed_simd = { version = "0.3", package = "packed_simd_2", features = ["into_bits"]}
